Exclude some repos
hackclub/contribute pull request #50
Opened 2024-01-15 02:49 UTC by ajs256

repos such as onboard, confessions, etc shouldn't be shown here because the issues don't reflect action items that any community member can pick up and work on

2024-01-18 14:05 UTC, grymmy requested changes
Please exclude infra - certainly wouldn't mind ppl looking at that stuff and potentially helping.

2024-01-19 19:43 UTC, maxwofford commented
Hmmmm, I'd kinda like to see onboard listed for this sort of task https://github.com/hackclub/OnBoard/issues/311

Maybe we just don't show the PR count?

2024-01-19 19:43 UTC, grymmy approved these changes

2026-04-28 16:33 UTC, 3kh0 approved these changes

2026-04-28 16:34 UTC, merged